In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%timeit my_arr2 = my_arr * 2

896 μs ± 6.78 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
%timeit my_list2 = my_list * 2

4.25 ms ± 281 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
print(arr2.shape)
print(arr2.ndim)

(2, 4)
2


In [18]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.full((2,3), 2)

array([[2, 2, 2],
       [2, 2, 2]])

In [22]:
arr = np.array([[1,2,3], [4,5,6]])
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [26]:
arr = np.arange(10)
arr[5:8] = 12
arr_slice = arr[5:8]
print(arr)
arr_slice[0] = 12345
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]
[    0     1     2     3     4 12345    12    12     8     9]


In [29]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
old_values = arr3d[0].copy()
print(old_values)

arr3d[0] = 42

print(arr3d[0])
print(old_values)

[[1 2 3]
 [4 5 6]]
[[42 42 42]
 [42 42 42]]
[[1 2 3]
 [4 5 6]]


In [37]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [39]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [58]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[ 0.52655157, -0.8603026 , -0.20789872, -2.03111884],
       [ 0.01724553,  0.83200901, -1.63123058,  2.53554572],
       [ 1.66194041, -0.21573613,  0.59887456,  0.50897353],
       [-0.85719042,  0.88558541, -0.80616648,  0.3348501 ]])

In [ ]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2,3))

In [100]:
rng = np.random.default_rng(seed=12345)
x = rng.standard_normal(8)
y = rng.standard_normal(8)

print(x)
print(y)
np.maximum(x,y)

[-1.42382504  1.26372846 -0.87066174 -0.25917323 -0.07534331 -0.74088465
 -1.3677927   0.6488928 ]
[ 0.36105811 -1.95286306  2.34740965  0.96849691 -0.75938718  0.90219827
 -0.46695317 -0.06068952]


array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

In [101]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

In [103]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [106]:
matrix = np.arange(15).reshape((3,5))
print(matrix)
np.mean(matrix, axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 2.,  7., 12.])

In [107]:
arr = np.arange(10)
np.save("some_array", arr)

In [108]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])